// Generated by https://quicktype.io

export interface ErrorResponse {
    error:               string;
    message:             string;
    validationErrorList: ValidationError[];
}

export interface ValidationError {
    field:   string;
    message: string;
}
